[window]
padding =  { x = 16 , y = 14}
opacity = 0.9
blur = true
decorations =  "None"


[font]
normal = { family = "CascaydiaMono Nerd Font", style = "Regular" }
bold   = { family = "CascaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CascaydiaMono Nerd Font", style = "Italic" }
size = 15.0



[cursor]
style = {shape = "Beam", blinking = "Always"}
 

